### ISSUE TITLE
WebSQL threw an error Error

### ISSUE THREAD

**Issue by ganeshmogare** [nolanlawson/cordova-plugin-sqlite-2#67] opened 2018-09-06 10:16 UTC
Issue
Hello ,
When i sync data from couchdb to pouchdb , first time it will work fine , but when close the app and relaunch , app will throw the following error

**WebSQL threw an error Error: Failed to allocate a 56000520 byte allocation with 25165824 free bytes and 49MB until OOM, max allowed footprint 174396912, growth limit 201326592**

Please note thet i'm using `cordova-plugin-sqlite-2`

Info
**Environment: Nodejs/Angularjs
Platform:Cordova Android
Adapter: pouchdb-adapter-cordova-sqlite
Server: CouchDB
Plugin : cordova-plugin-sqlite-2**

**Comment by nolanlawson** [comment] 2018-10-28 23:03
Is this on Android or iOS? Either way, it seems this could probably be fixed by changing the batch size in PouchDB/CouchDB. If your documents are very large then it could cause OOM (Out Of Memory) errors.

Please reopen if I diagnosed incorrectly, thanks for reporting.

**Closed by nolanlawson** 2018-10-28 23:03 UTC

**Comment by nolanlawson** [comment] 2018-10-28 23:06
seems to be a duplicate of https://github.com/nolanlawson/cordova-plugin-sqlite-2/issues/45#issuecomment-422217387
